### ISSUE TITLE
¿Qué tal crear un grupo de apoyo brasileño?

### ISSUE THREAD

**Issue by jeffersonalionco** [BrunoSobrino/TheMystic-Bot-MD#161]
@BrunoSobrino ¿Puedo crear un grupo no whatsapp de soporte brasileño (BR) y agregarlo al README.md principal del proyecto?

**Comment by BrunoSobrino** [comment]
@jeffersonalionco Disculpe por no responder antes, he tenido unos dias complicados. Claro! Puedes hacer el grupo y agregarlo al readme.md. Apenas pueda me unire al grupo. Nuevamente gracias por tu apoyo en mantener este proyecto.

**Comment by jeffersonalionco** [comment]
> @jeffersonalionco Disculpe por no responder antes, he tenido unos dias complicados. Claro! Puedes hacer el grupo y agregarlo al readme.md. Apenas pueda me unire al grupo. Nuevamente gracias por tu apoyo en mantener este proyecto.

@BrunoSobrino Ok, pronto pondré esta opción en el README.
