### ISSUE TITLE
Creación de Wiki: TheMystic BOT MD

### ISSUE THREAD

**Issue by jeffersonalionco** [BrunoSobrino/TheMystic-Bot-MD#179]
@ferhacks  Iniciativa para crear documentación para TheMystic-bot

**Comment by jeffersonalionco** [comment]
@BrunoSobrino  ¿Qué opinas de la Iniciativa?  https://github.com/BrunoSobrino/TheMystic-Bot-MD/wiki


Ya estoy creando estos comandos a continuación.

![comandos](https://github.com/BrunoSobrino/TheMystic-Bot-MD/assets/73146650/1a9cbc19-2b32-4719-b3d0-17be52a490bb)

**Comment by Skidy89** [comment]
hola, bruno sobrino se retiro de los bots. asi que tienes que hablar con el actual owner @ferhacks

**Comment by jeffersonalionco** [comment]
> hola, bruno sobrino se retiro de los bots. asi que tienes que hablar con el actual owner @ferhacks

Ok gracias te aviso entonces

**Comment by BrunoSobrino** [comment]
> hola, bruno sobrino se retiro de los bots. asi que tienes que hablar con el actual owner @ferhacks

Hola Skid XD, a este sujetoo si le he estado respondiendo. Ha estado colaborando con el Bot y añadiendo el multilenguaje

Aiden ha estado inactivo y el proyecto quedo en manos de todos los colaboradores. yo ando haciendo lo posible en mis tiempos libres y disponibles. Como lo anuncie en mi retiro oficial

Espero te encuentres bien Skid, un saludo!

**Comment by BrunoSobrino** [comment]
> @BrunoSobrino ¿Qué opinas de la Iniciativa? https://github.com/BrunoSobrino/TheMystic-Bot-MD/wiki
> 
> Ya estoy creando estos comandos a continuación.
> 
> ![comandos](https://private-user-images.githubusercontent.com/73146650/318556008-1a9cbc19-2b32-4719-b3d0-17be52a490bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTI5NzQsIm5iZiI6MTcxMjI5MjY3NCwicGF0aCI6Ii83MzE0NjY1MC8zMTg1NTYwMDgtMWE5Y2JjMTktMmIzMi00NzE5LWIzZDAtMTdiZTUyYTQ5MGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA0NTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNDFmZjUxNzgwODVlNjE3N2Q1NTEyOWEzZjc4NDc4MjMyYjg1MmViOWY3ZmE0Yjk4OTAwZTU5YTczZGI1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A05iI93vY7JJICTPMzUbiyAtVEhUZedN9m_7r7lm_Ys)

Hola! Me parece una idea increible, mas que nada para orientar a los nuevos usuarios que recien se implementan en este mundo de los Bots. Puedes crearlo y cualquier cosa que necesites me lo reportas por el issues de soporte general #155 para ayudarte con ello.

Como te comento el colaborador @Skidy89, yo ya estoy retirado de los temas relacionados con el Bot, sin embargo en tiempos libres estare ayudando con lo que pueda para mantener el proyecto vivo un tiempo mas, de igual forma pues queda en manos de todos los colabores. Se te agrade a ti y a todos los demas que colaboran en este proyecto.

**Comment by Skidy89** [comment]
saludos bruno, tu estas retirado. tu opinion es invalida

lo que seria mejor de esa wiki seria modificar un poco el handler para que edite el readme y poner el codigo como activo o con error

@BrunoSobrino te amo beibi

**Comment by BrunoSobrino** [comment]
> saludos bruno, tu estas retirado. tu opinion es invalida
> 
> lo que seria mejor de esa wiki seria modificar un poco el handler para que edite el readme y poner el codigo como activo o con error
> 
> @BrunoSobrino te amo beibi

Pa' empezar, invalido solo tú. XD

El problema con seguir agregando cosas al readme.md es que se esta volviendo muy largo y quedaria inleible por lo largo que esta. En su lugar con la wiki se puede reducir la info y solo dejar en la explicacion sobre el proyecto, los comandos  y todo eso.

Yo igual te amo my love @Skidy89 👉👈 (no homo) XD
