### ISSUE TITLE
Instalar Dependencia ""canvas"" Falla en DebianARM

### ISSUE THREAD

**Issue by weskerty** [BrunoSobrino/TheMystic-Bot-MD#204]
Debian ARM, intale todos los paquetes requeridos e igual me falla la instalacion. 
Alguien conoce alguna solucion?

[4/4] Building fresh packages...
[-/7] ⠠ waiting...
[-/7] ⠠ waiting...
[3/7] ⠠ canvas
[7/7] ⠠ sharp
error /root/mystic/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments:
Directory: /root/mystic/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@20.12.2 | linux | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@20.12.2 (node-v115 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.3
gyp info using node@20.12.2 | linux | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.3
gyp info using node@20.12.2 | linux | arm64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/root/mystic/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/root/mystic/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/root/mystic/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/root/mystic/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/mystic/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/mystic/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/mystic/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:204:21)
gyp ERR! System Linux 4.19.127-g8f70b11-dirty
gyp ERR! command "/usr/bin/node" "/root/mystic/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/root/mystic/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/root/mystic/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd /root/mystic/node_modules/canvas
gyp ERR! node -v v20.12.2
gyp ERR! node-gyp -v v3.6.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /root/mystic/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/root/mystic/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/mystic/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/mystic/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Linux 4.19.127-g8f70b11-dirty
node-pre-gyp ERR! command "/usr/bin/node" "/root/mystic/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /root/mystic/node_modules/canvas
node-pre-gyp ERR! node -v v20.12.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /root/mystic/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --updat

**Comment by jeffersonalionco** [comment]
**Si usa NPM INSTALL para instalar las dependencias, ¿no funciona?**

**Comment by weskerty** [comment]
> **Si usa NPM INSTALL para instalar las dependencias, ¿no funciona?**

Tira el mismo error con npm install y yarn install

**Comment by weskerty** [comment]
intenta descargar esto que no existe 
https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz

**Comment by jeffersonalionco** [comment]
> intenta descargar esto que no existe https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz

El error específico es que no se pudo encontrar Python. Node.js usa Python durante el proceso de compilación de algunos paquetes nativos, como canvas. El error indica que no se pudo encontrar el ejecutable de Python y sugiere configurar la variable de entorno PYTHON para resolver este problema.

Para solucionar este problema, debe asegurarse de que Python esté instalado en su sistema y que la variable de entorno PYTHON esté configurada para apuntar a la instalación correcta de Python. Esto permitirá que el proceso de creación del paquete Canvas se complete con éxito.

**Comment by jeffersonalionco** [comment]
Utilice el comando `python --version` para comprobar si está instalado o PYTHON. Si no está instalado, use el comando `sudo apt-get install python3.9`

entonces necesitas definir una variable de entorno de:
`Python export PYTHON=/ruta/al/ejecutable/de/python `      

Generalmente el camino es /usr/bin/python

Utilice uno de los siguientes comandos para recargar
`source ~/.bashrc`
`source ~/.bash_profile`

ESPERO QUE ESTO TE HAYA AYUDADO

> intenta descargar esto que no existe https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz

**Comment by weskerty** [comment]
> Utilice el comando `python --version` para comprobar si está instalado o PYTHON. Si no está instalado, use el comando `sudo apt-get install python3.9`

Gracias. Pero sucede el mismo error.
node18-gyp requiere Python2, yo tenia Python3
 
Instale Node22 con la esperanza de que Node22-gyp ya sea compatible con Python3 ya que no pude hacer funcionar pyenv y python2 no es instalable en Debian12

Probe en Debian11ARM con Python2 y el mismo error sucede. (404 al link)
Al parecer no hay una version para ARM64 de Canvas
En el Git de NodeCanvas esto le sucede a todos los que usan Mac con ARM de Apple

**Comment by weskerty** [comment]
Luego de esto el bot no funciona, no puede instalar canvas ni las dependencias que vienen despues.
Tuve que borrar game-glx.js y canvas del package.json para hacerlo funcionar de nuevo.

Lamentablemente no pude probar el juego. Manda un video de como era el juego 👉👈
Debian11ARM64
Node20
Python2.7 y Python3.9

**Comment by jeffersonalionco** [comment]
> Luego de esto el bot no funciona, no puede instalar canvas ni las dependencias que vienen despues. Tuve que borrar game-glx.js y canvas del package.json para hacerlo funcionar de nuevo.
> 
> Lamentablemente no pude probar el juego. Manda un video de como era el juego 👉👈 Debian11ARM64 Node20 Python2.7 y Python3.9

@weskerty No será necesario eliminar game-glx, ya he pensado en una solución al problema.

Esto facilitará el juego y mejorará el rendimiento.

Gracias por informar del error.

**Comment by jeffersonalionco** [comment]
@weskerty  ¡Tus problemas han sido resueltos! Gracias por todo.
