### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by ahmedmazika7** [BrunoSobrino/TheMystic-Bot-MD#234]

**Comment by ahmedmazika7** [comment]
بلاك و كدا

**Comment by weskerty** [comment]
كن أكثر توضيحًا بشأن مشكلتك وتفاصيل الخطأ والمكان الذي تقوم بتشغيل الروبوت منه.
استخدم أيضًا المترجم للكتابة باللغة الإنجليزية أو الإسبانية.
