### ISSUE TITLE
Como puedo ayudar a Traducir el juego Galaxy (glx)?

### ISSUE THREAD

**Issue by weskerty** [BrunoSobrino/TheMystic-Bot-MD#237]
Responde en Ptgs y no muchos entienden. Pense en cambiar todos las lineas en ptgs de el juego, pero eso es ineficiente en caso de que el juego se actualice y se pierda todo.

Como se agregan traducciones a los comandos desde `/language/es.json` ?

**Comment by BrunoSobrino** [comment]
Hola! El comando será truducido en estas semanas, es algo que tengo pendiente y por cuestiones de tiempo no he podido.
