### ISSUE TITLE
Error SumiFX - Yarn Install

### ISSUE THREAD

**Issue by weskerty** [BrunoSobrino/TheMystic-Bot-MD#239]
![image](https://github.com/BrunoSobrino/TheMystic-Bot-MD/assets/82781997/2e3cf2c1-dd1f-4cb7-b8f4-2cfebde8946b)
![image](https://github.com/BrunoSobrino/TheMystic-Bot-MD/assets/82781997/9a9c512c-c9ce-4231-8e98-a2171bbc27c9)

**Comment by BrunoSobrino** [comment]
> ![image](https://private-user-images.githubusercontent.com/82781997/344955704-2e3cf2c1-dd1f-4cb7-b8f4-2cfebde8946b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjU1NjYsIm5iZiI6MTcyMDM2NTI2NiwicGF0aCI6Ii84Mjc4MTk5Ny8zNDQ5NTU3MDQtMmUzY2YyYzEtZGQxZi00Y2I3LWI4ZjQtMmNmZWJkZTg5NDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE1MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjJiYzExYmRmYzdlMGFhMGE0OTczN2VkMDM1NTZiNTNjM2JmOWQ5ZjZhY2QzMzY5ODJhZDY3ZTBmZDBjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MHY4aN7T9KeVTpcZHkIyuczu-ce9zbN_bj4DeDpu46M) ![image](https://private-user-images.githubusercontent.com/82781997/344955865-9a9c512c-c9ce-4231-8e98-a2171bbc27c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjU1NjYsIm5iZiI6MTcyMDM2NTI2NiwicGF0aCI6Ii84Mjc4MTk5Ny8zNDQ5NTU4NjUtOWE5YzUxMmMtYzljZS00MjMxLThlOTgtYTIxNzFiYmMyN2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE1MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTVhNDQ5NjA3MzUzN2NkNmRjNmYxODM5MTVkM2QxMzMyZWZmZjVhN2E2NGM0ZTYwYmQ4OWIxNjBlYzQzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKrOPvx0JsGplzDId6Gt2CqKX_f97Vy5azvhv4jlF1Y)

El error ha sido corregido, el archivo modificado fue package.json.

Adicionalmente los siguientes comandos fueron corregidos:
- #letra 
- #spotify
- #fb
- #ig 

Y serán arreglados pronto:
- #ytmp3
- #ytmp4
- #spotifypro

Y otros problemas que puedan detectarse.

----------------------------

The bug has been fixed, the modified file was package.json.

Additionally, the commands were fixed:
- #letra 
- #spotify
- #fb
- #ig 

And they will be fixed soon:
- #ytmp3
- #ytmp4
- #spotifypro

And other problems that may be detected.
