### ISSUE TITLE
Ajustar el Bot Privado

### ISSUE THREAD

**Issue by weskerty** [BrunoSobrino/TheMystic-Bot-MD#281]
Actualmente el bot se activa en todos los grupos en los que esta. Hay alguna manera de hacer que todo este desactivado amenos de que se activen las funciones?

Actualmente hago banchat welcome off en cada chat. Pero estos datos se pierden si reinicio sesion.

**Comment by ToxiPain** [comment]
Puedes añadirle code para que se guarden en un .json o en database y no debería darte problemas cada que borres la sesión y puedes dejarle como off/on en predeterminado. Tengo entendido que todas las funciones, incluido el modoadmin o antigrupos/antipriv se guardan en el archivo de la sesión.

**Comment by weskerty** [comment]
> database y no debería darte problemas 

Por alguna razon pierde sus ajustes en caso de que inicie sesion nuevamente y debo bloquear todos los grupo uno por uno

**Comment by Skidy89** [comment]
realmente esto se esta volviendo un problema?
podemos cambiarlo a la propia db sin problemas
pero @BrunoSobrino tiene la ultima palabra

**Comment by manusoto1997** [comment]
> ¿Realmente esto se está volviendo un problema? podemos cambiarlo a la propia db sin problemas pero@BrunoSobrinoTiene la última palabra

Me meto también en la conversación para decir que porfa si JAJA al menos el welcome que es el más molesto de tener que estar desactivando...

**Comment by Skidy89** [comment]
Esta bien lo tomare en cuenta para hacerlo lo mas pronto posible
