### ISSUE TITLE
No puedo activar el Bot por BOXMINE

### ISSUE THREAD

**Issue by Leo-cyber-sys** [BrunoSobrino/TheMystic-Bot-MD#43]
Hola, eh tenido un inconveniente ala hora de crear el servidor en box mine, el soporte de tal app me sugirió q conversará con el sub bot algo así, no puedo activar el Bot desde q ah sido creado, puede ser una falla me dijeron
![Screenshot_20230222_133016_com android chrome](https://user-images.githubusercontent.com/125781107/220725205-fe21100d-099e-490e-b866-cc52f102b009.jpg)
Espero su ayuda...

**Comment by BrunoSobrino** [comment]
Por el momento aun no trabajo en una solución para el nodo7 de BoxMineHost. Avisare por aqui cuando lo haya.

**Comment by karim1702** [comment]
i have the same problem in replit
